[package]
name = "calorie-counting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "calorie_counter_lib"
path = "src/lib.rs"

[[bin]]
name = "calorie_counter"
path = "src/main.rs"


[dependencies]
